### ISSUE TITLE
Add LEDs to Omnid Main board to indicate battery levels

### ISSUE THREAD

**Issue by lliu11** [omnid/nuhal#8]
- [x] source LED (RGB with different colors to represent the different levels) 
- [x] change color of LED connected to the desired pins
- [ ] correlate battery levels to the LED color (green=good, yellow=need charging, red=too low immediate charging required) (issue #20)
- [ ] read battery level from Omnid and change the LED color (issue #20)
- [x] assign pins for adding to Omnid Main Board

**Comment by m-elwin** [comment]
We should think about using panel mount rather than board mount led's so that we can see them when the board is in a case.

**Comment by dlandry97** [comment]
I found these:
https://www.digikey.com/en/products/detail/visual-communications-company-vcc/5100H7/59897
https://www.digikey.com/en/products/detail/visual-communications-company-vcc/5100H5/59894
https://www.digikey.com/en/products/detail/visual-communications-company-vcc/5100H1/59891

**Comment by m-elwin** [comment]
Why has this been moved to "Ready for feedback?" What am I providing feedback on? There does not seem to be a PR
